### ISSUE TITLE
Updating past binutils 2.34?

### ISSUE THREAD

**Issue by asiekierka** [tkchia/binutils-ia16#10]
https://github.com/WonderfulToolchain/binutils-ia16/tree/binutils-2_38-ia16

This update should cause far fewer problems than the GCC 12 update. I only stumbled on one issue that wasn't a renaming situation and it was a header ordering/inclusion issue... However, I recommend testing ELKS and gold output - just in case. (Wonderful relies on segelf, so I've tested a little bit of that at least.)

Notably, binutils 2.34 -> 2.38 gets rid of the necessity for one IA16-specific hack (`#define FIRST_NEED_GOT_SYMBOL ...` in `gas/config/tc-i386.c`).

**Comment by tkchia** [comment]
Hello @asiekierka,

OK.  Incidentally, the `bfd/i386elks.c` back-end can probably be considered deprecated now &mdash; ELKS programs are now built as ELF using the `gold` linker, and then converted with `elf2elks`.  So there is no need to expend too much effort to port it.

Thank you!

**Comment by asiekierka** [comment]
https://github.com/WonderfulToolchain/binutils-ia16/tree/binutils-2_39-ia16

I've been using the 2.38 one for the WonderSwan toolchain's development for a while now, with no known issues. Today, I've started updated it to 2.39, and am about to start using that version likewise. The 2.38 -> 2.39 update caused no significant code changes that I'm aware of (the only conflicts were pertaining to the build system and/or DJGPP compilation patches), however it has caused some issues:

```
/tmp/ccimljBH.s: Assembler messages:
/tmp/ccimljBH.s:13: Error: 1-byte relocation cannot be applied to 2-byte field
```

I assume it pertains to `howto->size` being 1 instead of 2 here:

```c
  HOWTO(R_386_SEGRELATIVE, 4, 1, 16, false, 0, complain_overflow_bitfield,
        bfd_elf_generic_reloc, "R_386_SEGRELATIVE",
        true, 0xffff, 0xffff, false),
```

but I must ask - is there a reason for that size being 1 in the first place?

**Comment by asiekierka** [comment]
[The patch as mentioned above](https://github.com/WonderfulToolchain/binutils-ia16/commit/a350f9e67226344ad48f082855cba04d26f9984b) seems to work fine for my usecase (emitting segelf-relocated ELFs), allowing me to upgrade my tooling to binutils 2.39.

**Comment by tkchia** [comment]
Hello @asiekierka,

I have pulled your updates on top of 2.39 into my tree.  They seem to be passing the regression tests quite well, and I guess I will trust that you know what you are doing. :slightly_smiling_face: 

Thank you!

**Comment by tkchia** [comment]
Hello @asiekierka,

> but I must ask - is there a reason for that size being 1 in the first place?

I cannot recall, but probably I (mis)interpreted the `size` field as a shift rather than a byte count.  Thank you!

**Comment by asiekierka** [comment]
Trusting that I know what I'm doing is a bit of a bold claim, but thank you!

I care about trying to update pieces of the toolchain as a way to benefit from upstream feature updates and bugfixes - of course, binutils is much easier to update than a compiler backend, the latter remaining above my experience/skill level at this time...
