### ISSUE TITLE
libi86 tests are mostly failing

### ISSUE THREAD

**Issue by andrewbird** [tkchia/binutils-ia16#12]
Hello @tkchia, sorry to bother you but there seems to be a problem with your binutils that causes the libi86 tests to fail. Rather than post the copious logs, this snippet appears to me to be the salient part.

~~~
/usr/ia16-elf/libexec/libi86/tests/../tests/metacheck.at:50: $CC -o a.exe $CPPFLAGS -Wall -Werror=strict-prototypes -Werror=missing-prototypes -Werror=unused -Werror=deprecated -Werror=uninitialized -Werror=maybe-uninitialized -Os -mregparmcall -mdosx -mcmodel=small a.c -li86 -Wl,-Map=a.map
stderr:
/usr/lib/x86_64-linux-gnu/gcc/ia16-elf/6.3.0/../../../../../ia16-elf/bin/ld.gold: fatal error: cannot use --plugin: /usr/lib/x86_64-linux-gnu/gcc/ia16-elf/6.3.0/../../../../../ia16-elf/bin/ld.gold was compiled without plugin support
collect2: error: ld returned 1 exit status
stdout:
/usr/ia16-elf/libexec/libi86/tests/../tests/metacheck.at:50: exit code was 1, expected 0
4. metacheck.at:47: 4. C compiler toolchain (metacheck.at:47): FAILED (metacheck.at:50)
~~~

The test run https://github.com/andrewbird/dosemu2/actions/runs/3664118223 I saw it on is part of the Dosemu2 test suite, but I expect you'll see the same thing if you trigger a run on your libi86 project directly.

Thank you!

**Comment by asiekierka** [comment]
This is more of a [build-ia16 issue](https://github.com/tkchia/build-ia16/blob/master/build.sh#L999-L1008) than a binutils-ia16 issue, if anything.

Either way, where is `--plugin` coming from?

**Comment by andrewbird** [comment]
> Either way, where is --plugin coming from?

Sorry I have no idea about that. We just run the PPA packaged tests as supplied
Enumerate first
`/usr/ia16-elf/libexec/libi86/tests/testsuite --list`

then
```
/usr/ia16-elf/libexec/libi86/tests/testsuite --x-installcheck --x-test-underlying
      --x-with-dosemu=/path/to/dosemu    --x-with-dosemu-options ="-o test.out" NUMBER_OF_TEST
```

**Comment by tkchia** [comment]
Hello @andrewbird,

Sorry for that &mdash; let me try to see what is going on.  I just ported the `binutils-ia16` patches on top of upstream Binutils 2.39 (per @asiekierka 's branch), which is probably what is causing this error.  In fact I encountered some problems with `binutils-ia16` installing stuff (`libctf` and a `libdep.so`) in locations that conflict with the host-targeted (i.e. x86-64) Binutils.  Ugh ugh ugh.

Hello @asiekierka,

> Either way, where is `--plugin` coming from?

Good question indeed.  I am pretty sure that `gcc-ia16` does not need to use any linker plugins, so this is probably something I really have to figure out.

(**Edit:** apparently `gcc-ia16` tries to use a plugin for link-time optimization (LTO) when invoking the linker.  This is a bit strange as I do not enable LTO in the `libi86` tests.)

Thank you!

**Comment by tkchia** [comment]
Hello @andrewbird, hello @asiekierka,

I am also getting similar errors on my PPA's `libi86` builds.  Apparently the `cannot use --plugin` error occurs _only_ when trying to compile a program in `-mdosx` (i.e. protected mode DOS extender) mode.  :thinking:  Let me look into this further.

Thank you!

**Comment by tkchia** [comment]
@andrewbird : compiling with `-mdosx` should work now.  Please try again.  Thank you!

**Comment by andrewbird** [comment]
Thank you! As soon as it hits the PPA I'll give it a try.

**Comment by andrewbird** [comment]
Hello @tkchia,
The test run seems to be fine now https://github.com/andrewbird/dosemu2/actions/runs/3664118223

Thank you!

**Comment by tkchia** [comment]
@andrewbird : cool, thanks!
