### ISSUE TITLE
Enhanchment, Wishlist:  'New' Executables?

### ISSUE THREAD

**Issue by afarlie** [tkchia/binutils-ia16#3]
This may not be the focus of your efforts, but it would be nice if there you would consider adding the ability for these  tools to build so termed "New" Executable format binaries.  https://en.wikipedia.org/wiki/New_Executable

(posted here as I think it's a linker issue rather than compiler one as such)

Support in the linking (and compiling) that would enable Window 3.x era style applications (predominantly 16bit)  (.EXE), libraries (.DLL) and drivers (.DRV) to be built would be desirable, possibly for WINE's 16 bit support libraries,  and for making 'free' alternatives of 16 bit core libraries to be used with any potential WOWEXEC implementation in ReactOS. ( Windows 3.11 Enchanced mode drivers  used Linear Executables (.386) which could contain 16 and 32 bit code, which is outside the scope of your project as I see it)

Borland C/C++ (certainly in version 4.5),  also defined as series of Tiny/Small etc. models in relation to Far block layouts,  in respect of both DOS (MZ exe) and Windows style "New" executables.  Support for those models (if not already implemented) should be considered.

**Comment by tkchia** [comment]
Hello @afarlie,

> Borland C/C++ (certainly in version 4.5), also defined as series of Tiny/Small etc. models in relation to Far block layouts, in respect of both DOS (MZ exe) and Windows style "New" executables. Support for those models (if not already implemented) should be considered.

Thanks!  Well, the GCC IA-16 toolchain already has quite robust support for the "tiny" and "small" memory models for MS-DOS programs --- these are linked, respectively, as headerless `.com` files and `MZ`-style `.exe` files.

I had tried to implement the other memory models, starting with "medium" (far code, near data), but [have not been very successful](https://github.com/tkchia/gcc-ia16/issues/24).  I am open to contributions towards this direction. ☺️

Thank you!

**Comment by tkchia** [comment]
Hello @afarlie,

As for "New Executable" programs, I have not quite learnt enough about how they work, in order to get them implemented (the `NE` file format seems rather complex).  Again, contributions will be welcome.

Thank you!

**Comment by afarlie** [comment]
(As with any open source program,  "Working patches welcome!" :rofl: )

Open Watcom certainly had some support for NE, but it might not be a useful resource for stuff for licensing reasons.

NE seems to be mostly about generating the tables properly. (I'd suggest asking someone that's done development for WINE for a long time, which had a loader for them, or one of the ReactOS people.).  You might also want to look into  https://github.com/osfree-project/osfree/tree/master/DOS/WIN16 which was imported form a compatibility layer originally used in OS/2.  Knowing how the the loader potentially resolves things can help in understanding how the linker should be presenting it.

I also at some point made some notes here about 16 bit memory models  (https://reactos.org/wiki/User:Alex_farlie/16_Bit_compilers)

I'm not someone that's a low level programmer, to be able to contribute on something like binutils but  I'll list some possible resources below, if anyone else is listening.

Borland manuals for their devlepment tools around version 4.5 were quite quite detailed, If you can find copies (try archive.org's search or Google Books, there are very very useful. )

 Matt Peitrek wrote some books on Windows internals from around 1992-1995 ish.

Charles Petzold wrote a series of books on Windows Programming (see http://www.charlespetzold.com/books.html), which gave examples from the user side of Windows Development. (Some of his examples used a DEF file which were instructions to the linker about how to handle certain parts of a NEW Executable IIRC.)

I'd also suggest introducing yourself at https://msfn.org/board/ ( there are programmers/coders there that were able some-how to write code that directly patched into Windows 95/98 to make it do things that were considered impossible, they may be useful contacts to make. There may be users there with expertise that would assist in expanding the binutils-16 you are working on, or be able to advise on extending it at some future date if you wanted to do  a binutils-vxd for the Windows 3.11/95/98 era,  .VXD/.386 being the  16/32 bit driver format used in Windows Enhanced mode prior to NT's entirely 32 bit driver model. )

Also try looking through - http://www.mdgx.com/add.htm#DDK there may be some documentation in the Windows 95 era DDK about, various binary image formats.   The Windows 3.1 SDK is not online, so you might have to ask around to find a physical copy, but it had a lot more information on the New Executable file format I'm told.  

New Executable were also used with some early versions of OS/2,  I'm not aware of many OS/2 users or  forums, because that OS very quickly moved to 32 bit style Linear Executables.

**Comment by afarlie** [comment]
More infomation in depth : - http://program-transformation.org/Transform/NeFormat

**Comment by tkchia** [comment]
Hello @afarlie,

> (As with any open source program, "Working patches welcome!" :rofl: )

Never underestimate the power of working patches! 🙂  Well, some features are easier to implement --- or at least more urgent --- than others.  And `NE` support and "medium" model support seem to me to belong to the "not so easy" camp, though I am sure there is some latent demand for these things.

So what I can say is, they will happen when they happen. 🙂

Thank you!

**Comment by afarlie** [comment]
The code in the projects here might also prove informative,   https://github.com/topics/new-executable , 

https://github.com/alexfru/Win16asm (written for NASM)  also seems to have some 'helper functions' that might be of interest, ( albiet there's not much commenting.).

**Comment by afarlie** [comment]
Closing for now as I've been informed that in order to be able to fully support NE, the linker would also need to be able to handle  ia16-omf modules as well as a ia16-elf    I will be opening a separate issue.
