### ISSUE TITLE
Build error with latest GCC 9.2

### ISSUE THREAD

**Issue by mfld-fr** [tkchia/binutils-ia16#5]
Hello @tkchia,

First of all : happy new year :smiley: !

An ELKS user reported a problem while building the cross tools with GCC version 9.2.1 on Fedora 30.

I reproduced that problem with GCC 9.2.0 on Gentoo, while building `binutils`, commit 184ba458e1ab8e46d09c3dee48790e93141793f2:
```
gcc -DHAVE_CONFIG_H -I. -I../../binutils-src/binutils  -I. -I../../binutils-src/binutils -I../bfd -I../../binutils-src/binutils/../bfd -I../../binutils-src/binutils/../include -DLOCALEDIR="\"/home/mfld/advantech/elks-master/cross/share/locale\"" -Dbin_dummy_emulation=bin_vanilla_emulation  -W -Wall -Wstrict-prototypes -Wmissing-prototypes -Wshadow -Wstack-usage=262144 -Werror -I../../binutils-src/binutils/../zlib -g -O2 -MT wrstabs.o -MD -MP -MF .deps/wrstabs.Tpo -c -o wrstabs.o ../../binutils-src/binutils/wrstabs.c
Dans le fichier inclus depuis /usr/include/stdio.h:867,
                 depuis ../../binutils-src/binutils/sysdep.h:25,
                 depuis ../../binutils-src/binutils/wrstabs.c:25:
Dans la fonction « sprintf »,
    mis en ligne depuis « stab_start_class_type » à ../../binutils-src/binutils/wrstabs.c:1476:4:
/usr/include/bits/stdio2.h:36:10: erreur: l'argument de la directive « %s » est nul [-Werror=format-overflow=]
   36 |   return __builtin___sprintf_chk (__s, __USE_FORTIFY_LEVEL - 1,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   37 |       __bos (__s), __fmt, __va_arg_pack ());
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1 : tous les avertissements sont traités comme des erreurs
make[5]: *** [Makefile:1061: wrstabs.o] Error 1
make[5] : on quitte le répertoire « /mnt/data/usr/src/advantech/cross3/build/binutils-build/binutils »
make[4]: *** [Makefile:1103: all-recursive] Error 1
make[4] : on quitte le répertoire « /mnt/data/usr/src/advantech/cross3/build/binutils-build/binutils »
make[3]: *** [Makefile:748: all] Error 2
make[3] : on quitte le répertoire « /mnt/data/usr/src/advantech/cross3/build/binutils-build/binutils »
make[2]: *** [Makefile:3574: all-binutils] Error 2
make[2] : on quitte le répertoire « /mnt/data/usr/src/advantech/cross3/build/binutils-build »
make[1]: *** [Makefile:849: all] Error 2
make[1] : on quitte le répertoire « /mnt/data/usr/src/advantech/cross3/build/binutils-build »
make: *** [/home/mfld/advantech/elks-master/tools/Makefile:34: .binutils.build] Error 2
```
Looks like GCC 9.2.x is more strict... making the -Werror to fail... am I right ?

**Comment by tkchia** [comment]
Hello @mfld-fr,

> First of all : happy new year !

Happy new year to you too!

> Looks like GCC 9.2.x is more strict... making the -Werror to fail... am I right ?

Hmm... apparently this was also a known issue in GCC 8.x (https://gcc.gnu.org/bugzilla/show_bug.cgi?id=90036).  Apparently GCC was not able to deduce that `vstring` would be non-null at this point in the code:
```
      if (ownvptr)
	{
	  assert (info->type_stack->index > 0);
	  vtable = (char *) xmalloc (20);
	  sprintf (vtable, "~%%%ld", info->type_stack->index);
	}
      else
	{
	  vtable = (char *) xmalloc (strlen (vstring) + 3);
	  sprintf (vtable, "~%%%s", vstring);  /* <= */
	  free (vstring);
	}
```
One way to quickly work around this is to add an `assert (vstring);` before the `sprintf` call, as Martin Sebor suggested in the bug discussion.

Alternatively: I recently rebased my Binutils patches on top of a more recent branch (2.32) of mainline Binutils.  I _think_ that, among other things, it did happen to fix this problem.  So you might want to consider grabbing a more recent commit from my `binutils-ia16` repository. :-)

Thank you!

**Comment by mfld-fr** [comment]
For the alternative, what commit would you suggest to pick up, as I am a bit lost in your 'ia16' branches ?

**Comment by tkchia** [comment]
Hello @mfld-fr,

My most recently ["stable" tagged commit](https://github.com/tkchia/binutils-ia16/releases/tag/binutils-ia16-20190928) has been tested, and should do the job.  Thank you!

**Comment by mfld-fr** [comment]
Just tried with the latest 'stable' tag dated 2019-09-28 (commit 3fc69e3b2e9864a7357027a9c37c37fa6c55685d): no more error while building `binutils`.

Thanks for the quick support !
