### ISSUE TITLE
Compiling with gcc 10.1.0

### ISSUE THREAD

**Issue by cjsthompson** [tkchia/binutils-ia16#7]
Hi,

Since gcc was upgraded to 10.1.0, binutils-ia16 fails to build. Here's a screenshot of the problem:

![Screenshot_2020-05-22_16-22-12](https://user-images.githubusercontent.com/359383/82755522-59984380-9dd4-11ea-9e04-623f3be0261d.png)

**Comment by tkchia** [comment]
Hello @cjsthompson,

I will try to look into this.  Thank you!

**Comment by tkchia** [comment]
Hello @cjsthompson,

It seems that mainline Binutils fixed the problem by changing
```
  int num_group;
```
in `bfd/elf-bfd.h` to
```
  unsigned int num_group;
```
so perhaps you can try this as a quick fix first.

Meanwhile I will also see if I can rebase the `binutils-ia16` patches onto a more recent mainline Binutils version --- this should include the above fix, plus a whole slew of other changes.

Thank you!

**Comment by cjsthompson** [comment]
Thanks a lot. I'll do that.

**Comment by tkchia** [comment]
Hello @cjsthompson,

I have added my quick fix to `binutils-ia16` in the meantime, as commit https://github.com/tkchia/binutils-ia16/commit/6ce41ebeb63fac3ace24c5b34669f390fd2e88e4.  Thank you!
